import { NextResponse } from 'next/server'

// Calculator lead submissions get emailed to Corey
// This uses a simple mailto-style approach via the Gravity Forms API
// For now, we store leads and forward them via a simple fetch to the WP site

export async function POST(request) {
  try {
    const body = await request.json()
    const { name, phone, email, type, details } = body

    if (!name || !phone) {
      return NextResponse.json({ error: 'Name and phone are required' }, { status: 400 })
    }

    // Build a formatted message
    const message = [
      `New ${type || 'Calculator'} Lead from signlab.com.au`,
      ``,
      `Name: ${name}`,
      `Phone: ${phone}`,
      `Email: ${email || 'Not provided'}`,
      ``,
      `Estimate Details:`,
      details || 'No details provided',
      ``,
      `This lead was generated by the online ${type || 'cost'} calculator.`,
    ].join('\n')

    // Try to submit via Gravity Forms if configured
    const wpBaseUrl = process.env.NEXT_PUBLIC_GRAVITY_FORMS_API_URL || 'https://dashboard.signlab.com.au/wp-json'
    const consumerKey = process.env.NEXT_PUBLIC_GRAVITY_FORMS_CONSUMER_KEY
    const consumerSecret = process.env.NEXT_PUBLIC_GRAVITY_FORMS_CONSUMER_SECRET

    if (consumerKey && consumerSecret) {
      // Submit to Gravity Forms "Contact Us" form (ID 1)
      // Field IDs: 13=First name, 15=Last name, 19=Phone, 18=Email, 17=Company, 21=Message
      try {
        const gfResponse = await fetch(`${wpBaseUrl}/gf/v2/entries`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Basic ' + Buffer.from(`${consumerKey}:${consumerSecret}`).toString('base64'),
          },
          body: JSON.stringify({
            form_id: 1,
            13: name,
            19: phone,
            18: email || '',
            17: type || 'Calculator Lead',
            21: message,
          }),
        })

        if (gfResponse.ok) {
          return NextResponse.json({ success: true, method: 'gravity-forms' })
        }
        const errText = await gfResponse.text()
        console.error('Gravity Forms error:', gfResponse.status, errText)
      } catch (gfError) {
        console.error('Gravity Forms submission failed:', gfError)
      }
    }

    // Fallback: log the lead (will show in Vercel function logs)
    console.log('=== NEW CALCULATOR LEAD ===')
    console.log(message)
    console.log('=== END LEAD ===')

    return NextResponse.json({ success: true, method: 'logged' })
  } catch (error) {
    console.error('Lead submission error:', error)
    return NextResponse.json({ error: 'Failed to submit lead' }, { status: 500 })
  }
}
