// Master list of all suburb/area pages
// status: 'live' = page exists with full content, 'planned' = listed but not built yet
// Add new areas here as you build them — the areas index page and footer auto-update

export const allAreas = [
  // === LIVE PAGES (built and ready) ===
  {
    slug: 'vehicle-wraps-salisbury',
    name: 'Salisbury',
    type: 'Vehicle Wraps',
    region: 'North',
    status: 'live',
    description: 'Van wraps, ute wraps and fleet graphics for tradies across the northern suburbs.',
  },
  {
    slug: 'signage-adelaide-cbd',
    name: 'Adelaide CBD',
    type: 'Signage',
    region: 'Central',
    status: 'live',
    description: 'Shopfront signage, illuminated signs and window graphics for city centre businesses.',
  },
  {
    slug: 'vehicle-wraps-norwood',
    name: 'Norwood',
    type: 'Vehicle Wraps',
    region: 'East',
    status: 'live',
    description: 'Premium vehicle wraps for businesses on The Parade and across the eastern suburbs.',
  },

  // === PLANNED PAGES (coming soon — add content to suburbs.js to make them live) ===
  {
    slug: 'vehicle-wraps-prospect',
    name: 'Prospect',
    type: 'Vehicle Wraps & Signage',
    region: 'North',
    status: 'planned',
    description: 'Vehicle wraps and signage for businesses along Prospect Road and the inner north.',
  },
  {
    slug: 'signage-glenelg',
    name: 'Glenelg',
    type: 'Signage',
    region: 'South West',
    status: 'planned',
    description: 'Shopfront signage, A-frames and window graphics for Jetty Road businesses.',
  },
  {
    slug: 'vehicle-wraps-elizabeth',
    name: 'Elizabeth',
    type: 'Vehicle Wraps',
    region: 'North',
    status: 'planned',
    description: 'Fleet wraps and trade vehicle signage for the Elizabeth and Playford area.',
  },
  {
    slug: 'signage-port-adelaide',
    name: 'Port Adelaide',
    type: 'Signage & Vehicle Wraps',
    region: 'West',
    status: 'planned',
    description: 'Signage and vehicle wraps for the Port Adelaide industrial and maritime precinct.',
  },
  {
    slug: 'vehicle-wraps-mount-barker',
    name: 'Mount Barker',
    type: 'Vehicle Wraps',
    region: 'Adelaide Hills',
    status: 'planned',
    description: 'Vehicle wraps for the fastest-growing region in SA — tradies, farms and local businesses.',
  },
  {
    slug: 'signage-morphett-vale',
    name: 'Morphett Vale',
    type: 'Signage & Vehicle Wraps',
    region: 'South',
    status: 'planned',
    description: 'Signs and vehicle wraps for businesses across the southern suburbs.',
  },
  {
    slug: 'signage-unley',
    name: 'Unley',
    type: 'Signage',
    region: 'South',
    status: 'planned',
    description: 'Shopfront and heritage-sensitive signage for Unley Road and King William Road businesses.',
  },
  {
    slug: 'vehicle-wraps-marion',
    name: 'Marion',
    type: 'Vehicle Wraps',
    region: 'South',
    status: 'planned',
    description: 'Vehicle wraps and fleet branding near Westfield Marion and the southern corridor.',
  },
  {
    slug: 'signage-brighton',
    name: 'Brighton',
    type: 'Signage',
    region: 'South West',
    status: 'planned',
    description: 'Coastal business signage for Brighton, Seacliff and the beachside suburbs.',
  },
  {
    slug: 'vehicle-wraps-tea-tree-gully',
    name: 'Tea Tree Gully',
    type: 'Vehicle Wraps',
    region: 'North East',
    status: 'planned',
    description: 'Vehicle wraps for tradies and businesses across the north-eastern suburbs.',
  },
  {
    slug: 'signage-lonsdale',
    name: 'Lonsdale',
    type: 'Signage & Vehicle Wraps',
    region: 'South',
    status: 'planned',
    description: 'Industrial signage and fleet wraps for the Lonsdale business district.',
  },
  {
    slug: 'vehicle-wraps-modbury',
    name: 'Modbury',
    type: 'Vehicle Wraps',
    region: 'North East',
    status: 'planned',
    description: 'Vehicle wraps and signage for businesses around Tea Tree Plaza and Modbury.',
  },
  {
    slug: 'signage-mawson-lakes',
    name: 'Mawson Lakes',
    type: 'Signage & Vehicle Wraps',
    region: 'North',
    status: 'planned',
    description: 'Modern signage and wraps for the Mawson Lakes technology and business precinct.',
  },
  {
    slug: 'vehicle-wraps-adelaide-hills',
    name: 'Adelaide Hills',
    type: 'Vehicle Wraps & Signage',
    region: 'Adelaide Hills',
    status: 'planned',
    description: 'Vehicle wraps and signage for wineries, tourism and trade businesses in the Hills.',
  },
]
